[PPP-4899] Vulnerable Component: commons-io
pentaho/maven-parent-poms pull request #588
Opened 2024-08-13 20:51 UTC by singletonc

Jira: https://hv-eng.atlassian.net/browse/PPP-4899

- Update Apache Felix HTTP Bridge version to latest minor version, containing commons-io 2.15.0, which is 2.7+, addressing CVE-2021-29425

Related PRs:
https://github.com/pentaho/pentaho-kettle/pull/9525
https://github.com/pentaho/pentaho-reporting/pull/1678

2024-08-13 20:54 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-08-13 20:54 UTC, buildguy commented
### :white_check_mark: Build finished in 3m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2024-08-13 21:02 UTC, NJtwentyone requested changes
please identify QA tests per - https://hv-eng.atlassian.net/wiki/spaces/ENG/pages/31277645984/Recommended+process+when+reviewing+and+addressing+security+vulnerabilities

and please link or add comment to original jira issue

2024-08-30 19:25 UTC, rmansoor approved these changes

2024-09-16 19:54 UTC, NJtwentyone commented
> please identify QA tests per - https://hv-eng.atlassian.net/wiki/spaces/ENG/pages/31277645984/Recommended+process+when+reviewing+and+addressing+security+vulnerabilities
> 
> and please link or add comment to original jira issue

jira comment mentioning test case: https://hv-eng.atlassian.net/browse/PPP-4899?focusedCommentId=2050526

2024-09-16 19:54 UTC, NJtwentyone approved these changes

2024-09-16 19:54 UTC, merged